services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/backlog-games
    depends_on:
      - mongo
      - games-dashboard
    networks:
      - app-network

  games-dashboard:
    image: node:latest
    container_name: frontend
    working_dir: /app
    volumes:
      - ./games-dashboard:/app
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d/
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
